### ISSUE TITLE
RDA Values lookup is not working

### ISSUE THREAD

**Issue by anders-naslund** [omeka-s-modules/ValueSuggest#60]
When testing this module I've found that the connection to RDA is not returning any values. It doesn't matter which Reference value vocabularies I trying to use, nothing happens.
Inspecting the browser I can see a request like:
_admin/value-suggest/proxy?query=&lang=sv&type=valuesuggestall:rda:RDAContentType_
Which returns a status 200 OK with a JSON list like:
_suggestions: []_

Could you please investigate?

**Comment by jimsafley** [comment]
Thanks for bringing this to our attention. I've updated the RDA suggester to correctly parse the new output format. The fix is in the next version: [1.9.1](https://github.com/omeka-s-modules/ValueSuggest/releases/tag/v1.9.1).

**Comment by anders-naslund** [comment]
Downloaded 1.9.1 so I could test but receive errors when trying to save the Resource Template after removing all referenses to RDA lookup values
 Laminas\ServiceManager\Exception\ServiceNotCreatedException
Service with name "customvocab:6" could not be created. Reason: CustomVocab\Entity\CustomVocab entity with criteria {"id":6} not found

Details:

Omeka\Api\Exception\NotFoundException: CustomVocab\Entity\CustomVocab entity with criteria {"id":6} not found in /var/www/utv3.kulturhotell.se/web/application/src/Api/Adapter/AbstractEntityAdapter.php:686
Stack trace:
#0 /var/www/utv3.kulturhotell.se/web/application/src/Api/Adapter/AbstractEntityAdapter.php(404): Omeka\Api\Adapter\AbstractEntityAdapter->findEntity(Array, Object(Omeka\Api\Request))
#1 /var/www/utv3.kulturhotell.se/web/application/src/Api/Manager.php(230): Omeka\Api\Adapter\AbstractEntityAdapter->read(Object(Omeka\Api\Request))
#2 /var/www/utv3.kulturhotell.se/web/application/src/Api/Manager.php(115): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#3 /var/www/utv3.kulturhotell.se/web/modules/CustomVocab/src/Service/CustomVocabFactory.php(21): Omeka\Api\Manager->read('custom_vocabs', 6)
#4 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(765): CustomVocab\Service\CustomVocabFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'customvocab:6', NULL)
#5 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('customvocab:6')
#6 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(153): Laminas\ServiceManager\ServiceManager->get('customvocab:6')
#7 /var/www/utv3.kulturhotell.se/web/application/src/Api/Representation/ResourceTemplatePropertyRepresentation.php(144): Laminas\ServiceManager\AbstractPluginManager->get('customvocab:6')
#8 /var/www/utv3.kulturhotell.se/web/application/view/omeka/admin/resource-template/show.phtml(50): Omeka\Api\Representation\ResourceTemplatePropertyRepresentation->dataTypeLabels()
#9 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/utv3.k...')
#10 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#11 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#12 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#13 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#14 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#15 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#16 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#17 /var/www/utv3.kulturhotell.se/web/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#18 /var/www/utv3.kulturhotell.se/web/index.php(21): Laminas\Mvc\Application->run()
#19 {main}

**Comment by anders-naslund** [comment]
Sorry ... I see know that this error is related to another module :-)
